### PR TITLE
feat(lsp): apply text edits on confirmation

### LINKED ISSUE #81: Completion confirmation
Currently, when using lsp with `typescript-language-server` (`tsserver` in nvim-lspconfig) confirmation doesn't seem to trigger completion resolve, so automatic imports are not triggered.

I'm creating this issue to track [following](https://www.reddit.com/r/neovim/comments/l61gzb/builtin_lsp_client_exeprience/gkytdu6?utm_source=share&utm_medium=web2x&context=3)

### PR DESCRIPTION
**Pull request by rcarriga**
I thought I'd try to implement the text edits for LSP. I'm very new to Lua so please feel free to suggest better practices/methods. I've found it works for Pyright anyway.

Closes #81

### CODE REVIEW

**Comment by hrsh7th** [comment]
I have another solution.

**Comment by hrsh7th** [comment]
This PR is almost good but LSP expansion is more complex and missing `completionItem/resolve` so I will tackle it.

If this will be done, we don't need `vim-vsnip-integ` anymore. (but still need `snippets.nvim` or `vim-vsnip` etc)

**Comment by rcarriga** [comment]
Cool sounds good :+1: Feel free to close if you want

**Comment by hrsh7th** [comment]
Thank you for contribition.
#97 instead.

**Pull request closed without merging**
