### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by hrsh7th**

### CODE REVIEW

**Comment by tami5** [comment]
Finally :heart:

**Comment by hrsh7th** [comment]
This PR has a lot of breaking change so I will create PR for external sources.

I've defined the Public API.
I plan to keep it after this PR.
So the Public API signature is super important.

Please comments for this PR if someone don't like Public API's signature,

**Comment by hrsh7th** [comment]
I'm considering the API to get regexp pattern from custom source.

**Comment by tami5** [comment]
> This PR has a lot of breaking change so I will create PR for external sources.
> 
> I've defined the Public API.
> I plan to keep it after this PR.
> So the Public API signature is super important.
> 
> Please comments for this PR if someone don't like Public API's signature,

Does this pr include #44 ? Also it would be cool if this can be located in develop branch where other can test it until its mature then it can be merge to master

**Comment by hrsh7th** [comment]
Yes. It' included #44.

OK. I will create dev branch.

**Comment by tami5** [comment]
Nice I will switch to it in few days, it good to sync it with a this pr.

**Pull request merged**
