### PR TITLE
Use feedkeys

### LINKED ISSUE #78: `compe#complete` should use `feedkeys` internally.

### PR DESCRIPTION
**Pull request by hrsh7th**
Fixes #78, #74

### CODE REVIEW

**Comment by onsails** [comment]
when there is no completion candidates it fails with 
```
Error detected while processing function compe#confirm:
line    9:
E119: Not enough arguments for function: get
```

There is no such error with conditional map tho: `inoremap <silent><expr> <CR>      pumvisible() ? compe#confirm({ 'keys': "\<Plug>delimitMateCR", 'mode': '' }) : '<CR>'`

**Comment by hrsh7th** [comment]
Thank you testing.
I've updated PR. Please re-check it.

**Comment by onsails** [comment]
thank you for fixing!
It works correctly now.

**Comment by hrsh7th** [comment]
Thank you for testing. I've merged.

**Pull request merged**
