### PR TITLE
Improve context handling

### PR DESCRIPTION
**Pull request by hrsh7th**
toooooo difficult

### CODE REVIEW

**Comment by tami5** [comment]
Oh yah I've been bothered by seeing lsp suggestions in comments or have snippet suggestion while doing rust magic completion.

If you need any help or have a question just ping me 🙏

**Comment by hrsh7th** [comment]
It can't solve in this PR, I think.

I will check rust-analyzer's behavior.

**Comment by hrsh7th** [comment]
snippet suggestion can be solved (but that is not depends on this PR. We should implement in another PR).

**Comment by weilbith** [comment]
Could you maybe add some docs for this new feature? :upside_down_face:

**Comment by hrsh7th** [comment]
This PR is just a general improvement of context handling.

But one feature was added that will invoke new completion after confirmation by pressing `<CR>`, if if a trigger character has found.

**Comment by hrsh7th** [comment]
The new feature will be useful if you are writing css.

For example, old compe does not invoke new completion if `font-si|<CR>` -> `font-size: |;`.
But new compe will invoke completion so you can look `0em/0px/0em` as completion candidates.

**Comment by cloggier** [comment]
This doesn't seem to work for me. Then I type:
```
fo-si
```
I get `font-size` property completion item, but no snippet. Selecting property completion does not insert `;` at the end of the line nor it triggers another completion for units.

**Comment by hrsh7th** [comment]
Ah. Sorry.
If you use nvim-lspconfig, your css-ls is old.

I'm using `vscode-css-language-server`.
You can install it via `npm i -g vscode-langservers-extracted`

**Comment by cloggier** [comment]
It works, beautiful, thanks a lot!

**Comment by cloggier** [comment]
Ah, is it worth also replacing html and json server from those suggested in lspconfig? Are your versions superior?

**Comment by hrsh7th** [comment]
Yes. All my versions are better than old one.

**Pull request merged**
