### PR TITLE
datermine -> determine

### PR DESCRIPTION
**Pull request by timbedard**
@hrsh7th Assuming that the `datermine` function is meant to determine whether or not completion should occur for the source, here's a spelling typo correction PR. If this is not the case, let me know.

### CODE REVIEW

**Comment by hrsh7th** [comment]
Thank you!
You are correct, it's my bad.

I'm worrying to destructive change...

@tami5 @kristijanhusak @tamago324
Sorry. I will apply this change later.

**Comment by tami5** [comment]
I will update after the merge it should be a simple change

**Comment by timbedard** [comment]
It happens to us all. I whipped the PR up quick when I saw it because public APIs are more painful the longer you wait. 😂

**Comment by kristijanhusak** [comment]
Yeah go ahead and do it. I'll change it also.

**Comment by tamago324** [comment]
Thank you for contacting me.
I have just created a PR.
No problem to merge 👍

**Comment by hrsh7th** [comment]
Your guys are great.
Thank you.

**Pull request merged**
