### PR TITLE
docs: added demo

### PR DESCRIPTION
**Pull request by elianiva**
#118

### CODE REVIEW

**Comment by tami5** [comment]
Perhaps add the demos under demo table of content

**Comment by hrsh7th** [comment]
I think it ready to merge.

**Comment by tami5** [comment]
heading level of demos  should be `###` or may be `####`

**Comment by elianiva** [comment]
oopsie, I forgot to change that.

**Comment by elianiva** [comment]
Ok I think this is ready.

**Comment by hrsh7th** [comment]
I'm happy. Your guys are great contributers!

**Pull request merged**
