### PR TITLE
Add sticky_char (experimental)

### PR DESCRIPTION
**Pull request by hrsh7th**
see https://github.com/hrsh7th/nvim-compe/issues/120#issuecomment-773165747

### TODO
- [ ] Consideration
- [ ] Improve determine with sticky_char

### CODE REVIEW

**Review by lucax88x — APPROVED** [review]

**Comment by lucax88x** [comment]
is this correct as example configuration for trying this feature?

**Comment by hrsh7th** [comment]
Yes. It seems correct.

**Comment by lucax88x** [comment]
Looks better, but for some reason, it shows another LSP item as first, see mp4 below.

https://user-images.githubusercontent.com/6294464/106920101-09b39f80-670b-11eb-96a2-b5044a54454e.mp4

**Comment by hrsh7th** [comment]
It's weird.
It's,potential bug of matcher.lua maybe.

**Comment by lucax88x** [comment]
and after that, I can only see Buffer items in the completion? Dunno why

**Comment by hrsh7th** [comment]
I don't know.
Pleaes check with `let g:compe.debug = v:true`.

**Comment by lucax88x** [comment]
Ok, I can easily reproduce when I reload the file.


https://user-images.githubusercontent.com/6294464/106928531-91051100-6713-11eb-98e1-9c0296071993.mp4



probably not related to sticky, it's another bug.

**Comment by lucax88x** [comment]
where do I find debug logs? I've enable it.

**Comment by hrsh7th** [comment]
The debug log will be echoarea if Lua error occuered.

**Comment by hrsh7th** [comment]
Hm... I can't reproduce it even if I invoke `:e!`...

**Comment by hrsh7th** [comment]
I've pushed a improvement. if the commit does not solve problem, I have not idea.
https://github.com/hrsh7th/nvim-compe/commit/fdba285d2589162be1ffd6c764bdf0f8a549ecff

**Comment by lucax88x** [comment]
Same issue, I'll revisit the LSP attach part

**Pull request closed without merging**
