### PR TITLE
floating_preview

### LINKED ISSUE #12: [Feature Request]: nvim_lsp preview
...

### PR DESCRIPTION
**Pull request by hrsh7th**
Fixes #12

### CODE REVIEW

**Comment by hrsh7th** [comment]
The vsnip source integration has worked.

スクリーンショット 2020-11-17 22 20 55

**Comment by tami5** [comment]
Gist switch to documentation branch no preview with hovering over a snippet. Is there additional step I need to make todo testing?

**Comment by hrsh7th** [comment]
I think, no.
Currently `documentation` branch should work with vsnip.

**Comment by tami5** [comment]
hmm is tested on recent neovim branch? because I'm testing with vsnip but no preview

**Comment by hrsh7th** [comment]
I've implemented the documentation popup for nvim-lsp.

**Comment by tami5** [comment]
@hrsh7th I get Error `Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:452: Expected a ta
ble for Hover.contents` and still no preview :(

**Comment by tami5** [comment]
Looks nice

**Comment by hrsh7th** [comment]
I want padding, border and scrollbar but it's very hard to implement.

**Comment by tami5** [comment]
I agree a lot of users have told me this Checkout https://github.com/nvim-lua/plenary.nvim/tree/master/lua/plenary/window it has amazing api to understand neovim windows api better

**Comment by hrsh7th** [comment]
I'm considering to define `Widget` that uses `FloatingWindow` for primitive element.

The `FloatingWindow` is the primitive window utility.
The `Widget` makes complex UI element by using `FloatingWindow` utility in my thoughts.

For example, If we create window with padding that realized by the below code in my thoughts.

```viml
let s:Widget = compe#vital#import('VS.Widget');

let s:window_with_padding = s:Widget.new({ props -> [
\   {
\     'row': props.row,
\     'col': props.col,
\     'width': props.width + 4,
\     'height': props.height + 2
\   },
\   {
\     'row': props.row + 2,
\     'col': props.col + 1,
\     'width': props.width,
\     'height': props.height
\   },
\ ] })

call s:window_with_padding.open({
\   'row': ...,
\   'col': ...
\ })
```

**Comment by hrsh7th** [comment]
But I can't promise for implementing it.

**Comment by hrsh7th** [comment]
Anyway, you couldn't get the correct result with this branch.

Could you tell me which language server do you using?

**Comment by tami5** [comment]
> Anyway, you couldn't get the correct result with this branch.
> 
> Could you tell me which language server are you using?

I've only tested it on sumneko_lua , but later today I will test more servers.

**Comment by hrsh7th** [comment]
In my environment, works fine with sumneko_lua...

スクリーンショット 2020-11-17 23 43 09

**Comment by tami5** [comment]
I got preview with vimls, now vsnip works. 
Nothing works, let me check maybe in my config is the issue

**Comment by tami5** [comment]
Disabled all my config for lua server, still the same issue, let me try to update the server

**Comment by tami5** [comment]
Did reinstall of lua server, still same issue damn, I will try again tom

**Comment by tami5** [comment]
Is the scope this branch is only for preview popup?

**Comment by hrsh7th** [comment]
Yes. This branch only scoped the preview popup.

Hm... I will check my sumneko setting.

BTW, When using sumneko_lua, To display documentation popup depends on each item.

For example, `local` does not show document but `load` will show document.

**Comment by tami5** [comment]
@hrsh7th okay okay yes load showed. Thanks for saving me from further debugging :smile: 

I've been having a lot of issue with this server, after updating my neovim to last branch and nvim_lsp, my settings for some reason not working as it used to be, like enabling completion for vim.

**Comment by tami5** [comment]
Yah if just scoped, better to rename it to feat: floating preview

**Comment by hrsh7th** [comment]
I think it's ok to merge.

Should I rename `documentation.vim` to `floating_preview.vim`?

**Comment by tami5** [comment]
I suggest keeping it open for enhancement. I'm trying to have time tomorrow to navigate the code and perhaps contribute stuff

**Comment by hrsh7th** [comment]
Okay, thanks!

Currently, the implementation didn't debounced but I think it's,ok for now.

**Comment by tami5** [comment]
Also @hrsh7th whats with the capital letter naming convention? 😵 its a bit wired, first noticed with this codebase  . maybe object could be accepted but file names is a bit to much, don't you think? 

Did you read lua style guide before ?

common style is so important to facilitate contribution

**Comment by tami5** [comment]
If you allow me I can go over the vim and lua codebase and adhere to some style guide and convention

**Comment by hrsh7th** [comment]
My currently convention is...

1. Class name should be 'CamelCaae'
2. Some other identifier should be 'snake_case'
3. File name should be 'snake_case'

I don't know what is convention in the Lua.

I don't think to change Vim convention now.

**Comment by hrsh7th** [comment]
But off cource. I allow to you to fix some wording, decision dor convention.

**Comment by tami5** [comment]
I just found a style for lua
for lua https://github.com/Olivine-Labs/lua-style-guide

Couldn't find anything for vimscript. 

I suggest having snake for naming (both class and others, although i prefer one word for classes (e.g. if floating_window is class, float is better name)

BTW I use to hate though coming from js but after reading more code by the community I understood each language has its own stuff that its good to adopt to make reading across codebase with same language easily.

I strongly recommend following common and popular style so that new comers can easily read the code.

**Comment by tami5** [comment]
Whats vital namespace

**Comment by hrsh7th** [comment]
Your gessing is right :)
I often using JavaScript.

Hm... but if we don't use CamelCase for classes, it's quiet bad for reading, I thought.

Probable, we don't choose OOP in Lua?

**Comment by tami5** [comment]
@hrsh7th Yes, js and ts also c++ share this awesome camalCase style. But languages like clojure name-func is so common that it would so wired to find someone writing NameFunc or nameFunc or name_func. 

Code style guide and conventions is important because the define expectations. Imagine going to McDonald expecting a burger and find out that they are selling pizza :D. Nothing against pizza, you may like it but you’ve expected to find burgers.


I’m going to open pr tom

**Comment by hrsh7th** [comment]
I can allow for short naming and snake_case but I don't think it could be fitting to OOP...
What do,tou think about it?

**Comment by tami5** [comment]
class naming is as same as function and variable naming, it depends on the language. So I think classes should follow the same convention. One thing to keep in mind is that class in lua and vim is usually bound to a file name so its obvious. for example `window/init.lua` might mean that window is a class or a collection of function related to window. Also `window/float.lua, might mean that float is subclass or a collection of function related to float under the namespace/class window

**Comment by hrsh7th** [comment]
Hm... So I would prefer `new_xxx` method for module.

For example, luv uses this convention (e.g.: vim.loop.new_timer)

I can xgoose it.

**Comment by tami5** [comment]
Well I too would stronglyyyyyy prefer to see window.new_float instead of float:new. this way the main class/namespace has abstraction over subclasses or subnamespaces

**Comment by tami5** [comment]
Hey @hrsh7th  after you marge this to master I can start. In the future we can create another pr for enhancing preview windows.

**Comment by hrsh7th** [comment]
Okay, I've merged it.

**Comment by tami5** [comment]
@hrsh7th nice am working on compe/init.lua and in 30 min I will start the pr and hopefully we can start collaborating on making the codebase more "programmer friendly :laughing: "

**Pull request merged**
